MOCK_EMAILS = [
    {
        "id": "email_001",
        "thread_id": "thread_client_acme_001",
        "provider": "mock",
        "provider_message_id": "mock_msg_001",
        "provider_thread_id": "mock_thread_client_acme_001",
        "sender": "Sarah Johnson",
        "sender_email": "sarah.johnson@acmegroup.com",
        "recipient_email": "osama@cspsolutions.com",
        "subject": "Follow-up on the AI dashboard proposal",
        "date": "July 16, 2026",
        "received_at": "2026-07-16T09:30:00",
        "body": "Hi Osama, thank you for the previous proposal. We reviewed it internally and would like to schedule a call to discuss the AI dashboard scope, timeline, and estimated cost.",
        "preview": "We reviewed the proposal and would like to schedule a call...",
        "summary": "",
        "is_read": False,
        "reviewed": False,
        "starred": False,
        "tags": [],
        "category": "Client Email",
        "confidence_score": 0,
        "reason": "",
        "suggested_action": "",
        "is_client_related": True,
        "is_subscription_related": False,
        "is_unimportant_or_ad": False,
        "detected_provider": "",
        "has_previous_contact": True,
    },
    {
        "id": "email_002",
        "thread_id": "thread_client_dubai_001",
        "provider": "mock",
        "provider_message_id": "mock_msg_002",
        "provider_thread_id": "mock_thread_client_dubai_001",
        "sender": "Khaled Mansour",
        "sender_email": "khaled@dubaitech.ae",
        "recipient_email": "support@cspsolutions.com",
        "subject": "Issue with last integration update",
        "date": "July 16, 2026",
        "received_at": "2026-07-16T11:10:00",
        "body": "Hello CSP team, after the latest integration update, our team noticed that the report export is not showing the expected data. Could you please check this today?",
        "preview": "After the latest integration update, our team noticed...",
        "summary": "",
        "is_read": False,
        "reviewed": False,
        "starred": False,
        "tags": [],
        "category": "Client Support",
        "confidence_score": 0,
        "reason": "",
        "suggested_action": "",
        "is_client_related": True,
        "is_subscription_related": False,
        "is_unimportant_or_ad": False,
        "detected_provider": "",
        "has_previous_contact": True,
    },
    {
        "id": "email_003",
        "thread_id": "thread_marketing_001",
        "provider": "mock",
        "provider_message_id": "mock_msg_003",
        "provider_thread_id": "mock_thread_marketing_001",
        "sender": "Marketing Weekly",
        "sender_email": "newsletter@marketingweekly.com",
        "recipient_email": "osama@cspsolutions.com",
        "subject": "10 AI tools you should try this week",
        "date": "July 16, 2026",
        "received_at": "2026-07-16T12:15:00",
        "body": "Here are the top AI tools and productivity apps trending this week. Click here to read more and subscribe to our premium newsletter.",
        "preview": "Here are the top AI tools and productivity apps trending...",
        "summary": "",
        "is_read": False,
        "reviewed": False,
        "starred": False,
        "tags": [],
        "category": "Newsletter",
        "confidence_score": 0,
        "reason": "",
        "suggested_action": "",
        "is_client_related": False,
        "is_subscription_related": False,
        "is_unimportant_or_ad": True,
        "detected_provider": "",
        "has_previous_contact": False,
    },
    {
        "id": "email_004",
        "thread_id": "thread_promo_001",
        "provider": "mock",
        "provider_message_id": "mock_msg_004",
        "provider_thread_id": "mock_thread_promo_001",
        "sender": "Cloud Deals",
        "sender_email": "offers@clouddeals.com",
        "recipient_email": "it@cspsolutions.com",
        "subject": "Limited time discount on hosting",
        "date": "July 15, 2026",
        "received_at": "2026-07-15T15:45:00",
        "body": "Save 40% on cloud hosting plans. This is a promotional message sent to technology teams and startup companies.",
        "preview": "Save 40% on cloud hosting plans...",
        "summary": "",
        "is_read": False,
        "reviewed": False,
        "starred": False,
        "tags": [],
        "category": "Promotion",
        "confidence_score": 0,
        "reason": "",
        "suggested_action": "",
        "is_client_related": False,
        "is_subscription_related": False,
        "is_unimportant_or_ad": True,
        "detected_provider": "",
        "has_previous_contact": False,
    },
    {
        "id": "email_005",
        "thread_id": "thread_adobe_001",
        "provider": "mock",
        "provider_message_id": "mock_msg_005",
        "provider_thread_id": "mock_thread_adobe_001",
        "sender": "Adobe Billing",
        "sender_email": "billing@adobe.com",
        "recipient_email": "finance@cspsolutions.com",
        "subject": "Your Creative Cloud plan renewal",
        "date": "July 14, 2026",
        "received_at": "2026-07-14T08:20:00",
        "body": "Your Adobe Creative Cloud plan renews on July 28, 2026. Your subscription will continue using the saved payment method unless canceled before the renewal date. Amount: $59.99.",
        "preview": "Your Creative Cloud plan renews on July 28, 2026...",
        "summary": "",
        "is_read": True,
        "reviewed": False,
        "starred": False,
        "tags": [],
        "category": "Subscription",
        "confidence_score": 0,
        "reason": "",
        "suggested_action": "",
        "is_client_related": False,
        "is_subscription_related": True,
        "is_unimportant_or_ad": False,
        "detected_provider": "Adobe",
        "has_previous_contact": False,
    },
    {
        "id": "email_006",
        "thread_id": "thread_notion_001",
        "provider": "mock",
        "provider_message_id": "mock_msg_006",
        "provider_thread_id": "mock_thread_notion_001",
        "sender": "Notion Billing",
        "sender_email": "billing@notion.so",
        "recipient_email": "finance@cspsolutions.com",
        "subject": "Workspace subscription receipt",
        "date": "July 13, 2026",
        "received_at": "2026-07-13T10:00:00",
        "body": "Thank you for renewing your Notion workspace subscription. Workspace: CSP Solutions. Plan: Notion Business. Billing Period: July 13, 2026 to August 12, 2026. Amount Paid: $16.00.",
        "preview": "Thank you for renewing your Notion workspace subscription...",
        "summary": "",
        "is_read": True,
        "reviewed": False,
        "starred": False,
        "tags": [],
        "category": "Subscription",
        "confidence_score": 0,
        "reason": "",
        "suggested_action": "",
        "is_client_related": False,
        "is_subscription_related": True,
        "is_unimportant_or_ad": False,
        "detected_provider": "Notion",
        "has_previous_contact": False,
    },
    {
        "id": "email_007",
        "thread_id": "thread_zoom_001",
        "provider": "mock",
        "provider_message_id": "mock_msg_007",
        "provider_thread_id": "mock_thread_zoom_001",
        "sender": "Zoom Billing",
        "sender_email": "billing@zoom.us",
        "recipient_email": "it@cspsolutions.com",
        "subject": "License renewal confirmation",
        "date": "July 12, 2026",
        "received_at": "2026-07-12T13:40:00",
        "body": "Your Zoom license has been renewed successfully. Your current plan will remain active for the next billing cycle. Amount charged: $149.90.",
        "preview": "Your Zoom license has been renewed successfully...",
        "summary": "",
        "is_read": True,
        "reviewed": False,
        "starred": False,
        "tags": [],
        "category": "Subscription",
        "confidence_score": 0,
        "reason": "",
        "suggested_action": "",
        "is_client_related": False,
        "is_subscription_related": True,
        "is_unimportant_or_ad": False,
        "detected_provider": "Zoom",
        "has_previous_contact": False,
    },
    {
        "id": "email_008",
        "thread_id": "thread_aws_001",
        "provider": "mock",
        "provider_message_id": "mock_msg_008",
        "provider_thread_id": "mock_thread_aws_001",
        "sender": "AWS Billing",
        "sender_email": "billing@aws.amazon.com",
        "recipient_email": "cloud@cspsolutions.com",
        "subject": "Monthly usage invoice available",
        "date": "July 10, 2026",
        "received_at": "2026-07-10T09:15:00",
        "body": "Your AWS invoice for June 2026 is ready to view. The invoice includes cloud hosting, compute, storage, and data transfer usage. Total: $342.60.",
        "preview": "Your AWS invoice for June 2026 is ready to view...",
        "summary": "",
        "is_read": True,
        "reviewed": False,
        "starred": False,
        "tags": [],
        "category": "Cloud Invoice",
        "confidence_score": 0,
        "reason": "",
        "suggested_action": "",
        "is_client_related": False,
        "is_subscription_related": True,
        "is_unimportant_or_ad": False,
        "detected_provider": "AWS",
        "has_previous_contact": False,
    },
    {
        "id": "email_009",
        "thread_id": "thread_godaddy_001",
        "provider": "mock",
        "provider_message_id": "mock_msg_009",
        "provider_thread_id": "mock_thread_godaddy_001",
        "sender": "GoDaddy Renewals",
        "sender_email": "renewals@godaddy.com",
        "recipient_email": "it@cspsolutions.com",
        "subject": "Domain renewal reminder",
        "date": "June 29, 2026",
        "received_at": "2026-06-29T16:30:00",
        "body": "Your domain subscription is close to expiration. Renew before it expires to avoid DNS, hosting, and email service interruption.",
        "preview": "Your domain subscription is close to expiration...",
        "summary": "",
        "is_read": True,
        "reviewed": False,
        "starred": False,
        "tags": [],
        "category": "Domain Renewal",
        "confidence_score": 0,
        "reason": "",
        "suggested_action": "",
        "is_client_related": False,
        "is_subscription_related": True,
        "is_unimportant_or_ad": False,
        "detected_provider": "GoDaddy",
        "has_previous_contact": False,
    },
    {
        "id": "email_010",
        "thread_id": "thread_client_old_001",
        "provider": "mock",
        "provider_message_id": "mock_msg_010",
        "provider_thread_id": "mock_thread_client_old_001",
        "sender": "Maya Haddad",
        "sender_email": "maya@levantretail.com",
        "recipient_email": "osama@cspsolutions.com",
        "subject": "Re: Website support agreement",
        "date": "July 11, 2026",
        "received_at": "2026-07-11T14:10:00",
        "body": "Hi Osama, following our previous emails, can you confirm whether the support agreement includes monthly performance reports?",
        "preview": "Following our previous emails, can you confirm whether...",
        "summary": "",
        "is_read": False,
        "reviewed": False,
        "starred": False,
        "tags": [],
        "category": "Client Email",
        "confidence_score": 0,
        "reason": "",
        "suggested_action": "",
        "is_client_related": True,
        "is_subscription_related": False,
        "is_unimportant_or_ad": False,
        "detected_provider": "",
        "has_previous_contact": True,
    },
]


def get_mock_emails():
    return MOCK_EMAILS


def get_mock_email_by_id(email_id):
    for email in MOCK_EMAILS:
        if email["id"] == email_id:
            return email

    return None


def get_mock_emails_by_thread_id(thread_id):
    return [
        email
        for email in MOCK_EMAILS
        if email["thread_id"] == thread_id
    ]


def mark_mock_email_as_reviewed(email_id):
    email = get_mock_email_by_id(email_id)

    if not email:
        return None

    email["reviewed"] = True

    return email


def add_mock_email_tag(email_id, tag_name):
    email = get_mock_email_by_id(email_id)

    if not email:
        return None

    cleaned_tag = tag_name.strip()

    if not cleaned_tag:
        return None

    if cleaned_tag not in email["tags"]:
        email["tags"].append(cleaned_tag)

    return email